import './globals.css'
import { Inter } from 'next/font/google'
import Header from './views/header/header'
import Footer from './views/footer/footer'
import Hero from './views/hero/hero'
import Hero2 from './views/hero2/hero2'
import Hero3 from './views/hero3/hero3'
import Hero4 from './views/hero4/hero4'
import Hero5 from './views/hero5/hero5'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      
      <body className={inter.className}><Header></Header>
      <Hero></Hero> <Hero2></Hero2> <Hero3></Hero3> <Hero4></Hero4> <Hero5></Hero5>
      {children} <Footer></Footer>
        </body>
    </html>
  )
}
